#!/bin/bash
# Optimus SessionStart hook.
#
# This repo has no build and no test suite — it is an operating brain. So this
# hook does not install anything. Its job is to put LIVE state in front of the
# session before the first reply, because the thing that keeps going wrong is
# not a missing fact, it is a stale one repeated confidently.
#
# CLAUDE.md already auto-loads, so re-printing it would be waste. What this adds
# is the part a static file cannot know: how OLD the CURRENT STATE block is, and
# what the machines are doing right now.
#
# Must stay fast — it runs synchronously, before Patrick gets an answer. Every
# network call is bounded and every failure degrades to a printed line rather
# than a dead session.

set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-/home/user/optimus-map-tools}"
BRAIN="$ROOT/CLAUDE.md"
FEED="https://raw.githubusercontent.com/patricksiado-prog/Go-High-Level-MCP-2026-Complete/claude/optimus-map-tools-setup-6dcl6o/optimus/_feed"

echo "=============================================================="
echo " OPTIMUS — LIVE STATE AT SESSION START"
echo " Generated by .claude/hooks/session-start.sh. Everything below"
echo " is measured right now, not read out of the brain file."
echo "=============================================================="
echo

# ---------------------------------------------------------------- staleness
# The CURRENT STATE block at the top of CLAUDE.md is the only part of the brain
# that claims to be true NOW. If it has not been touched in days, it is a
# historical document wearing a present-tense voice — which is exactly how
# "register for the 20M-cell beta" survived four sessions unchecked.
if [ -f "$BRAIN" ]; then
  STAMP=$(grep -m1 '^# CURRENT STATE' "$BRAIN" 2>/dev/null | sed 's/.*updated //' || true)
  if [ -n "${STAMP:-}" ]; then
    SD=$(printf '%s' "$STAMP" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' || true)
    echo "BRAIN STATE BLOCK last updated: $STAMP"
    if [ -n "${SD:-}" ]; then
      A=$(( ( $(date +%s) - $(date -d "$SD" +%s 2>/dev/null || echo 0) ) / 86400 ))
      if   [ "$A" -ge 3 ]; then echo "  *** $A DAYS OLD — treat every line in it as UNVERIFIED. Re-check before quoting. ***"
      elif [ "$A" -ge 1 ]; then echo "  ($A day(s) old — re-verify anything you are about to tell Patrick.)"
      else                      echo "  (updated today)"
      fi
    fi
  else
    echo "BRAIN STATE BLOCK: not found — CLAUDE.md may have lost its CURRENT STATE header."
  fi
  echo
fi

# ---------------------------------------------------------------- scanner
# The hunter pushes a heartbeat to GitHub. It is NOT authoritative for whether
# rows are landing (it has shown healthy while zero rows were written), but it
# does say whether a run exists and how far it got.
HB=$(curl -s --max-time 8 "$FEED/heartbeat.json" 2>/dev/null || true)
if [ -n "${HB:-}" ] && printf '%s' "$HB" | grep -q run_id; then
  RID=$(printf '%s' "$HB" | grep -o '"run_id"[^,]*' | head -1 | cut -d'"' -f4)
  PH=$(printf '%s'  "$HB" | grep -o '"last_phase"[^,]*' | head -1 | cut -d'"' -f4)
  UP=$(printf '%s'  "$HB" | grep -o '"updated_at"[^,]*' | head -1 | cut -d'"' -f4)
  echo "SCANNER heartbeat: run $RID | phase '$PH' | heartbeat written $UP"
  case "$PH" in
    start|"") echo "  Stuck at launch is a known failure — if this has not advanced, the run died early." ;;
    sweep_start|pass_done) echo "  Reached the sweep. That means it logged in and opened the sheet." ;;
  esac
else
  echo "SCANNER heartbeat: COULDN'T READ (network blocked or feed empty) — say so, do not guess."
fi
echo
echo "  The heartbeat does NOT prove rows are landing. The authoritative check is"
echo "  get_file_metadata on workbook 1FhO2BTMXGefm1tLwKbbMPXvzT1160882Auauzep7ooA:"
echo "  a moving modifiedTime with a FLAT fileSize means it is being touched but"
echo "  nothing is being written. Run that before telling Patrick it is working."
echo

# ---------------------------------------------------------------- last session
echo "WHAT THE LAST SESSION SHIPPED:"
git -C "$ROOT" log --oneline -5 2>/dev/null | sed 's/^/  /' || echo "  (git unavailable)"
echo

echo "--------------------------------------------------------------"
echo "Open by telling Patrick state, not by asking him questions. If"
echo "he tells you a decision or a constraint, write it into the"
echo "CURRENT STATE block and push in the SAME turn — anything left"
echo "in chat dies with this session."
echo "--------------------------------------------------------------"
exit 0
