services:
  - type: web
    name: optimus-portal
    runtime: python
    plan: free
    rootDir: portal
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_CREDS_JSON
        sync: false
